In [96]:
import numpy as np
import pandas as pd

In [97]:
# Q1 — Series Fundamentals
s = pd.Series([10,20,30,40,50], index=["a","b","c","d","e"])
print(s.dtype)
print(s.values)
print(s.index)
print(s["c"])
print(s.values[2])

int64
[10 20 30 40 50]
Index(['a', 'b', 'c', 'd', 'e'], dtype='str')
30
30

In [98]:
# Q2 — DataFrame Creation
data = {
    "Name" : ["Alice","Bob","Charlie","David"],
    "Age" : [21,22,20,23],
    "City" : ["Mumbai","Pune","Delhi","Nashik"]
}
df = pd.DataFrame(data)
print(df.shape)
print(df.ndim)
print(df.columns)
print(df.index)
print(df.dtypes)
print(df["Name"])
print(df["Age"])
print(df.head(1))
print(df.head(2))
print(df[["Name","City"]])

(4, 3)
2
Index(['Name', 'Age', 'City'], dtype='str')
RangeIndex(start=0, stop=4, step=1)
Name      str
Age     int64
City      str
dtype: object
0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: str
0    21
1    22
2    20
3    23
Name: Age, dtype: int64
    Name  Age    City
0  Alice   21  Mumbai
    Name  Age    City
0  Alice   21  Mumbai
1    Bob   22    Pune
      Name    City
0    Alice  Mumbai
1      Bob    Pune
2  Charlie   Delhi
3    David  Nashik

In [99]:
# Q3 — External Data
df1 = pd.read_csv("services.csv")
print(df1.shape)
print(df1.columns)
print(type(df1.index))
print(df1.dtypes)

(23, 22)
Index(['id', 'location_id', 'program_id', 'accepted_payments',
       'alternate_name', 'application_process', 'audience', 'description',
       'eligibility', 'email', 'fees', 'funding_sources',
       'interpretation_services', 'keywords', 'languages', 'name',
       'required_documents', 'service_areas', 'status', 'wait_time', 'website',
       'taxonomy_ids'],
      dtype='str')
<class 'pandas.RangeIndex'>
id                           int64
location_id                  int64
program_id                 float64
accepted_payments              str
alternate_name                 str
application_process            str
audience                       str
description                    str
eligibility                    str
email                          str
fees                           str
funding_sources                str
interpretation_services        str
keywords                       str
languages                      str
name                           str
required_documents             str
service_areas                  str
status                         str
wait_time                      str
website                        str
taxonomy_ids                   str
dtype: object

In [100]:
# Q4 — Dtype Selection
df = pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Age": [20, 21, 19],
    "Salary": [50000.0, 60000.0, 45000.0]
})
print(df)
df.select_dtypes(include="number")
df.select_dtypes(include="str")

  Name  Age   Salary
0    A   20  50000.0
1    B   21  60000.0
2    C   19  45000.0

  Name
0    A
1    B
2    C

In [101]:
# Q5 — Boolean Indexing
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [17, 25, 31, 16, 28],
    "Score": [80, 65, 92, 74, 88]
})
print(df[df["Age"] > 18])
print(df[df["Score"] > 80])
print(df[(df["Age"] > 18) & (df["Score"] > 80)])
print(df[(df["Age"] > 18) & (df["Score"] > df["Score"].mean())].Name)

  Name  Age  Score
1    B   25     65
2    C   31     92
4    E   28     88
  Name  Age  Score
2    C   31     92
4    E   28     88
  Name  Age  Score
2    C   31     92
4    E   28     88
2    C
4    E
Name: Name, dtype: str

In [102]:
# Q6 — Missing Values
df = pd.DataFrame({
    "A": [10, 20, None, 40],
    "B": [1, None, 3, 4],
    "C": [None, None, None, 5]
})
print(df)
print(df.isnull().sum())
print(df.dropna())
print(df.dropna(axis=1))
print(df["A"].fillna(df["A"].mean()))
print(df["B"].fillna(0))

      A    B    C
0  10.0  1.0  NaN
1  20.0  NaN  NaN
2   NaN  3.0  NaN
3  40.0  4.0  5.0
A    1
B    1
C    3
dtype: int64
      A    B    C
3  40.0  4.0  5.0
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]
0    10.000000
1    20.000000
2    23.333333
3    40.000000
Name: A, dtype: float64
0    1.0
1    0.0
2    3.0
3    4.0
Name: B, dtype: float64

In [103]:
# Q7 — Duplicates
df = pd.DataFrame({
    "Name": ["A", "B", "A", "C", "B"],
    "Score": [80, 90, 80, 70, 90]
})
print(df[df.duplicated()])
print(df.duplicated().sum())
print(df.drop_duplicates())

  Name  Score
2    A     80
4    B     90
2
  Name  Score
0    A     80
1    B     90
3    C     70

In [104]:
# Q8 — GroupBy
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales"],
    "Employee": ["A", "B", "C", "D", "E"],
    "Salary": [50000, 60000, 45000, 55000, 70000]
})
print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Salary"].max())
print(df.groupby("Department")["Employee"].size())

Department
HR       50000.0
IT       55000.0
Sales    70000.0
Name: Salary, dtype: float64
Department
HR       55000
IT       60000
Sales    70000
Name: Salary, dtype: int64
Department
HR       2
IT       2
Sales    1
Name: Employee, dtype: int64

In [105]:
# Q9 — Handling Missing Values and Aggregating Data
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR", "Sales", "Sales"],
    "Employee": ["A", "B", "C", "D", "E", "F"],
    "Salary": [50000, 60000, 45000, None, 70000, 65000]
})
df["Salary"].isnull()
df.fillna({"Salary": df["Salary"].median()}, inplace= True)
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].mean().idxmax()
df

  Department Employee   Salary
0         IT        A  50000.0
1         IT        B  60000.0
2         HR        C  45000.0
3         HR        D  60000.0
4      Sales        E  70000.0
5      Sales        F  65000.0

In [106]:
# Q10 — String Operations
df = pd.DataFrame({
    "text": [
        "Hello Data Science",
        "I love Machine Learning",
        "Pandas is useful"
    ]
})
df["Lower"] = df["text"].str.lower()
df["Length"] = df["text"].str.len()
df["Startswith"] = df["text"].str.startswith("I")
df["Words"] = df["text"].apply(lambda x : len(x.split()))
df

                      text                    Lower  Length  Startswith  Words
0       Hello Data Science       hello data science      18       False      3
1  I love Machine Learning  i love machine learning      23        True      4
2         Pandas is useful         pandas is useful      16       False      3

In [107]:
# Q11 — Datetime
df = pd.DataFrame({
    "date": ["2026-01-15", "2026-02-20", "2026-03-10"]
})
df["Date"] = pd.to_datetime(df["date"])
print(df["Date"].dt.year)
print(df["Date"].dt.month)
print(df["Date"].dt.day)
print(df["Date"].dt.day_name())
df["7 Days Later"] = df["Date"] + pd.Timedelta(days=7)
df

0    2026
1    2026
2    2026
Name: Date, dtype: int32
0    1
1    2
2    3
Name: Date, dtype: int32
0    15
1    20
2    10
Name: Date, dtype: int32
0    Thursday
1      Friday
2     Tuesday
Name: Date, dtype: str

         date       Date 7 Days Later
0  2026-01-15 2026-01-15   2026-01-22
1  2026-02-20 2026-02-20   2026-02-27
2  2026-03-10 2026-03-10   2026-03-17

In [ ]:
# Master Practice Set
# Q1 Inspect, Selection, Missing Values, Group Analysis and Feature Creation
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "IT"],
    "Age": [22, 25, 21, 30, np.nan, 24],
    "Salary": [50000, 45000, 55000, 70000, 48000, np.nan],
    "Experience": [1, 3, 1, 6, 4, 2]
})
print(df)

print(df.shape)
print(df.dtypes)
print(df.isnull().sum())
print(df.describe())

print(df[["Name","Salary"]])
print(df[df["Age"]>23])
print(df[["Name","Salary"]][df["Experience"] >= 3])

print(df.isnull())
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

print(df.groupby("Department")["Salary"].mean())
print(df.groupby("Department")["Experience"].max())
print(df.groupby("Department")["Name"].size())
print(df.groupby("Department")["Salary"].mean().idxmax())

df["Annual_Salary_per_Experience"] = df["Salary"]/df["Experience"]
df
max_index = df['Annual_Salary_per_Experience'].idxmax()
top_employee = df.loc[max_index, 'Name']
print(top_employee)

  Name Department   Age   Salary  Experience
0    A         IT  22.0  50000.0           1
1    B         HR  25.0  45000.0           3
2    C         IT  21.0  55000.0           1
3    D      Sales  30.0  70000.0           6
4    E         HR   NaN  48000.0           4
5    F         IT  24.0      NaN           2
(6, 5)
Name              str
Department        str
Age           float64
Salary        float64
Experience      int64
dtype: object
Name          0
Department    0
Age           1
Salary        1
Experience    0
dtype: int64
             Age        Salary  Experience
count   5.000000      5.000000    6.000000
mean   24.400000  53600.000000    2.833333
std     3.507136   9864.076237    1.940790
min    21.000000  45000.000000    1.000000
25%    22.000000  48000.000000    1.250000
50%    24.000000  50000.000000    2.500000
75%    25.000000  55000.000000    3.750000
max    30.000000  70000.000000    6.000000
  Name   Salary
0    A  50000.0
1    B  45000.0
2    C  55000.0
3    D  70000.0
4    E  48000.0
5    F      NaN
  Name Department   Age   Salary  Experience
1    B         HR  25.0  45000.0           3
3    D      Sales  30.0  70000.0           6
5    F         IT  24.0      NaN           2
  Name   Salary
1    B  45000.0
3    D  70000.0
4    E  48000.0
    Name  Department    Age  Salary  Experience
0  False       False  False   False       False
1  False       False  False   False       False
2  False       False  False   False       False
3  False       False  False   False       False
4  False       False   True   False       False
5  False       False  False    True       False
Department
HR       46500.000000
IT       52866.666667
Sales    70000.000000
Name: Salary, dtype: float64
Department
HR       4
IT       2
Sales    6
Name: Experience, dtype: int64
Department
HR       2
IT       3
Sales    1
Name: Name, dtype: int64
Sales
C

In [ ]:
# Q2
employees = pd.DataFrame({
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Team": ["ML", "ML", "Data", "Data", "ML", "Backend", "Backend"],
    "Experience": [2, 5, 3, np.nan, 4, 6, 1],
    "Salary": [50000, 90000, 65000, 70000, np.nan, 85000, 45000],
    "Projects": [2, 7, 4, 5, 6, 8, 1]
})
print(employees)
employees["Experience"] = employees["Experience"].fillna(employees["Experience"].median())
employees["Salary"] = employees["Salary"].fillna(employees["Salary"].median())
print(employees[(employees["Experience"] > 3) & (employees["Projects"] >= 5)][["Employee", "Team", "Salary",]])
average_salary_of_each_team = employees.groupby("Team")["Salary"].mean()
print(average_salary_of_each_team)
team_with_the_highest_average_salary = average_salary_of_each_team.idxmax()
print(team_with_the_highest_average_salary)
employees["Projects_per_Year"] = employees["Projects"]/employees["Experience"]
employees.loc[employees["Projects_per_Year"].idxmax(),"Employee"]

bonus = pd.DataFrame({
    "Employee": ["A", "B", "C", "E", "F"],
    "Bonus": [5000, 10000, 7000, 8000, 12000]
})
employees = pd.merge(employees,bonus,how="left")
print(employees["Employee"][employees["Bonus"].isnull()])
employees["Bonus"] = employees["Bonus"].fillna(0)
employees["Total_Compensation"] = employees["Salary"] + employees["Bonus"] 
employees.loc[employees[employees["Team"] == "ML"]["Total_Compensation"].idxmax(),"Employee"]

  Employee     Team  Experience   Salary  Projects
0        A       ML         2.0  50000.0         2
1        B       ML         5.0  90000.0         7
2        C     Data         3.0  65000.0         4
3        D     Data         NaN  70000.0         5
4        E       ML         4.0      NaN         6
5        F  Backend         6.0  85000.0         8
6        G  Backend         1.0  45000.0         1
  Employee     Team   Salary
1        B       ML  90000.0
3        D     Data  70000.0
4        E       ML  67500.0
5        F  Backend  85000.0
Team
Backend    65000.000000
Data       67500.000000
ML         69166.666667
Name: Salary, dtype: float64
ML
3    D
6    G
Name: Employee, dtype: str

'B'